# Generated by Django 3.1.5 on 2021-01-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('material', models.CharField(choices=[('go', 'Gold'), ('si', 'Silver'), ('ku', 'Kupfer'), ('br', 'Bronze')], default='go', max_length=2)),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SammlerReihe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='coins/')),
                ('default', models.BooleanField(default=False)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.coin')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='reihe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.sammlerreihe'),
        ),
    ]
