# Generated by Django 3.1.5 on 2021-01-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='year',
            field=models.IntegerField(),
        ),
    ]
