# Generated by Django 3.1.5 on 2021-01-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20210130_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecoin',
            name='image',
            field=models.ImageField(upload_to='media/coins/'),
        ),
    ]
