# Generated by Django 3.1.6 on 2021-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_auto_20210210_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
