# Generated by Django 3.1.6 on 2021-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_coin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecoin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coins'),
        ),
    ]
